language: c

rvm:
  - "1.9.3"

compiler:
  - gcc

before_install:
 - echo "yes" | sudo add-apt-repository ppa:ubuntugis/ppa
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install libgeos-3.3.8 libgeos-c1 libgeos-dev
 - sudo apt-get install cmake

before_script:
 - mkdir build
 - cd build
 - cmake -DGPKG_GEOS:BOOL=on -DGPKG_TEST:BOOL=on -DGPKG_COVERAGE:BOOL=on ..

script:
 - make
 - ctest --output-on-failure

after_success:
  - mkdir coverage
  - cd coverage
  - ruby ../../coveralls.rb -v ../gpkg/CMakeFiles/gpkg_ext.dir
